/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 11d0072bb3738e36243d9165caf8f84c)
interface __BaseEnv_Env {
	S3_ENDPOINT: "https://example.r2.cloudflarestorage.com";
	S3_REGION: "auto";
	S3_BUCKET: "files";
	UPLOAD_URL_TTL_SECONDS: "600";
	DOWNLOAD_URL_TTL_SECONDS: "604800";
	ALLOWED_CONTENT_TYPES: "image/png,image/jpeg,image/webp";
	UPLOAD_TOKEN: string;
	S3_ACCESS_KEY_ID: string;
	S3_SECRET_ACCESS_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "S3_ENDPOINT" | "S3_REGION" | "S3_BUCKET" | "UPLOAD_URL_TTL_SECONDS" | "DOWNLOAD_URL_TTL_SECONDS" | "ALLOWED_CONTENT_TYPES" | "UPLOAD_TOKEN" | "S3_ACCESS_KEY_ID" | "S3_SECRET_ACCESS_KEY">> {}
}
