/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.example.jsonc --include-runtime=false` (hash: 1575024058f645357078826f58268406)
interface __BaseEnv_Env {
	S3_ENDPOINT: "https://YOUR_ACCOUNT_ID.r2.cloudflarestorage.com";
	S3_REGION: "auto";
	S3_BUCKET: "your-private-bucket";
	UPLOAD_URL_TTL_SECONDS: "600";
	DOWNLOAD_URL_TTL_SECONDS: "604800";
	UPLOAD_TOKEN: string;
	S3_ACCESS_KEY_ID: string;
	S3_SECRET_ACCESS_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "S3_ENDPOINT" | "S3_REGION" | "S3_BUCKET" | "UPLOAD_URL_TTL_SECONDS" | "DOWNLOAD_URL_TTL_SECONDS" | "UPLOAD_TOKEN" | "S3_ACCESS_KEY_ID" | "S3_SECRET_ACCESS_KEY">> {}
}
